name: Daily Automation

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Decode and Store Service Account Files
        run: |
          mkdir -p secrets
          echo "${{ secrets.SERVICE_FILE }}" | base64 --decode > secrets/SERVICE_FILE.json
          echo "${{ secrets.TTS_SERVICE_FILE }}" | base64 --decode > secrets/TTS_SERVICE_FILE.json
          
          # ✅ Properly append environment variables to GITHUB_ENV
          echo "SERVICE_FILE_PATH=$(pwd)/secrets/SERVICE_FILE.json" >> $GITHUB_ENV
          echo "TTS_SERVICE_FILE_PATH=$(pwd)/secrets/TTS_SERVICE_FILE.json" >> $GITHUB_ENV
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> $GITHUB_ENV
          echo "GEMINI_API=${{ secrets.GEMINI_API }}" >> $GITHUB_ENV

      - name: Verify Decoded Files Exist
        run: ls -l secrets/

      - name: Print First 5 Lines of SERVICE_FILE.json
        run: head -n 5 secrets/SERVICE_FILE.json

      - name: Verify Environment Variables
        run: env | grep 'SERVICE_FILE_PATH\|SHEET_ID\|GEMINI_API'

      - name: Run Script
        run: python automation.py

      - name: Cleanup Secrets
        run: rm -rf secrets
