name: Daily Automation

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC (Change as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set Up Environment Variables
        run: |
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> $GITHUB_ENV
          echo "GEMINI_API=${{ secrets.GEMINI_API }}" >> $GITHUB_ENV
          echo "SERVICE_FILE=$(echo '${{ secrets.SERVICE_FILE }}' | base64 --decode)" >> $GITHUB_ENV
          echo "SERVICE_FILE=$(echo '${{ secrets.TTS_SERVICE_FILE }}' | base64 --decode)" >> $GITHUB_ENV


      - name: Run Script
        run: python automation.py
